name: managing_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # utility packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_slidable: ^3.1.1

  # state management
  get: ^4.6.5
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/side_items.png
    - assets/icons/food.png
    - assets/icons/favorited.png
    - assets/icons/drinks.png
    - assets/icons/categories.png
    - assets/logo/logo.png
    - assets/images/burgers/BBQ Bacon Burger.jpg
    - assets/images/burgers/Classic cheese burger.jpg
    - assets/images/burgers/Double Decker Burger.jpg
    - assets/images/burgers/Spicy Chicken Burger.jpg
    - assets/images/burgers/Veggie Delight Burger.jpg
    - assets/images/desserts/Apple Pie.jpg
    - assets/images/desserts/Brownie Sundae.jpg
    - assets/images/desserts/Cheesecake.jpg
    - assets/images/desserts/Chocolate Lava Cake.jpg
    - assets/images/desserts/Tiramisu.jpg
    - assets/images/drinks/Classic Lemonade.jpg
    - assets/images/drinks/Green Tea.jpg
    - assets/images/drinks/Hot Chocolate.jpg
    - assets/images/drinks/Iced Coffee.jpg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
